default:

  components: "node_modules/"
  dist: "public/javascripts/dist/"

  apps:
    poem: "public/javascripts/src/poem/"
    add: "public/javascripts/src/add/"

  vendor:
    jquery: "jquery/dist/jquery.js"
    underscore: "lodash/dist/lodash.js"
    backbone: "backbone/backbone.js"
    marionette: "backbone.marionette/lib/backbone.marionette.js"
    localstorage: "backbone.localstorage/backbone.localStorage.js"
    bootstrap: "bootstrap/dist/js/bootstrap.js"
    d3: "d3/d3.js"
