default:

  components: "public/javascripts/components/"
  payload: "public/javascripts/payloads/"

  apps:
    poem: "public/javascripts/applications/poem/"
    add: "public/javascripts/applications/add/"

  vendor:
    jquery: "jquery/jquery.js"
    underscore: "underscore/underscore.js"
    backbone: "backbone/backbone.js"
    marionette: "marionette/lib/backbone.marionette.js"
    eventbinder: "Backbone.EventBinder/lib/backbone.eventbinder.js"
    wreqr: "Backbone.Wreqr/lib/backbone.wreqr.js"
    localstorage: "Backbone.localStorage/backbone.localStorage.js"
    bootstrap: "bootstrap/bootstrap/js/bootstrap.js"
    d3: "d3/d3.js"
