default:

  components: "public/javascripts/bower_components/"
  dist: "public/javascripts/dist/"

  apps:
    poem: "public/javascripts/src/poem/"
    add: "public/javascripts/src/add/"

  vendor:
    jquery: "jquery/jquery.js"
    underscore: "underscore/underscore.js"
    backbone: "backbone/backbone.js"
    marionette: "marionette/lib/backbone.marionette.js"
    eventbinder: "Backbone.EventBinder/lib/backbone.eventbinder.js"
    wreqr: "Backbone.Wreqr/lib/backbone.wreqr.js"
    localstorage: "backbone.localStorage/backbone.localStorage.js"
    bootstrap: "bootstrap/docs/assets/js/bootstrap.js"
    d3: "d3/d3.js"
