default:
  sliceInterval: 300
  visibleWords: 200

testing:
  db:
    uri: "mongodb://localhost/oversoul_testing"
development:
  db:
    uri: "mongodb://localhost/oversoul_development"
staging:
  db:
    uri: "mongodb://localhost/oversoul_staging"
production:
  db:
    uri: "mongodb://localhost/oversoul_production"
