testing:
  db:
    uri: "mongodb://localhost/spyder_testing"
development:
  db:
    uri: "mongodb://localhost/spyder_development"
staging:
  db:
    uri: "mongodb://localhost/spyder_staging"
production:
  db:
    uri: "mongodb://localhost/spyder_production"
