
default:
  sliceInterval:  300
  visibleWords:   200
  submissionVal:  100
  decayLifetime:  20000

testing:
  db: "mongodb://localhost/eh_testing"
development:
  db: "mongodb://localhost/eh_development"
staging:
  db: "mongodb://localhost/eh_staging"
production:
  db: "mongodb://localhost/eh_production"
