
default:
  port:           3000
  sliceInterval:  300
  visibleWords:   200
  submissionVal:  100
  decayLifetime:  20000
  lockRatio:      0.1

testing:
  db: "mongodb://localhost/oversoul_testing"
development:
  db: "mongodb://localhost/oversoul_development"
staging:
  db: "mongodb://localhost/oversoul_staging"
production:
  db: "mongodb://localhost/oversoul_production"
